//
//  AuthorizationScreenModels.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthorizationScreen {
    // MARK: Use cases
    
    enum SaveUser {
        struct Request {
            let userEmail: String?
            let userName: String?
            let userPassword: String?
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum Login {
        struct Request {
            let userEmail: String?
            let userPassword: String?
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum CheckIfUserAvailable {
           struct Request {
           }
           
           struct Response {
           }
           
           struct ViewModel {
           }
       }
    
    enum ChangeTextFieldHeight {
        struct Request {
            let segmentedTitle: String
        }
        
        struct Response {
            let heightConstant: CGFloat
        }
        
        struct ViewModel {
            let heightConstant: CGFloat
        }
    }
}

