//
//  AuthorizationScreenPresenter.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationScreenPresentationLogic {
    func presentUser(response: AuthorizationScreen.Login.Response)
    func presentNewUser(response: AuthorizationScreen.SaveUser.Response)
    func presentNewTextFieldHeight(response: AuthorizationScreen.ChangeTextFieldHeight.Response)
}

class AuthorizationScreenPresenter: AuthorizationScreenPresentationLogic {
    
    weak var viewController: AuthorizationScreenDisplayLogic?
    
    // MARK: Do something
    
    func presentUser(response: AuthorizationScreen.Login.Response) {
        viewController?.displayUser(viewModel: AuthorizationScreen.Login.ViewModel(error: response.error))
    }
    
    func presentNewUser(response: AuthorizationScreen.SaveUser.Response) {
        if let error = response.textError {
            let viewModel = AuthorizationScreen.SaveUser.ViewModel(errorMessage: error.description)
            viewController?.displayNewUser(viewModel: viewModel)
        } else {
            viewController?.displayNewUser(viewModel: AuthorizationScreen.SaveUser.ViewModel(errorMessage: nil))
        }
    }
    
    func presentNewTextFieldHeight(response: AuthorizationScreen.ChangeTextFieldHeight.Response) {
        let viewModel = AuthorizationScreen.ChangeTextFieldHeight.ViewModel(heightConstant: response.heightConstant)
        viewController?.displayNameTextFieldNewsHeight(viewModel: viewModel)
    }
}
