//
//  ChatScreenInteractor.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol ChatsScreenBusinessLogic {
    func doLogout(request: ChatsScreen.Logout.Request)
    func fetchUserName(request: ChatsScreen.FetchUserName.Request)
    func fetchMessages(request: ChatsScreen.FetchMessages.Request)
}

protocol ChatsScreenDataStore {
    //var name: String { get set }
}

class ChatsScreenInteractor: ChatsScreenBusinessLogic, ChatsScreenDataStore {
    
    var presenter: ChatsScreenPresentationLogic?
    var worker: ChatsScreenWorker?
    
    func doLogout(request: ChatsScreen.Logout.Request) {
        do {
            try Auth.auth().signOut()
        } catch {
            return
        }
        let response = ChatsScreen.Logout.Response()
        presenter?.userHasLogouted(response: response)
    }
    
    func fetchUserName(request: ChatsScreen.FetchUserName.Request) {
        guard let userId = Auth.auth().currentUser?.uid else { return }
        let reference = Database.database().reference(withPath: "users").child(userId)
        reference.observeSingleEvent(of: .value) { [weak self] (snapshot) in
            let user = User(snapshot: snapshot)
            self?.presenter?.presentUserName(response: ChatsScreen.FetchUserName.Response(user: user))
        }
    }
    
    func fetchMessages(request: ChatsScreen.FetchMessages.Request) {
        guard let userId = Auth.auth().currentUser?.uid else { return }
        let ref = Database.database().reference(withPath: "userMassages").child(userId)
        ref.observe(.childAdded) { [weak self] (snapshot) in
            let messageFromId = snapshot.key
            let userMessage = ref.child(messageFromId)
            userMessage.observe(.childAdded) { (snapshot) in
                let messageId = snapshot.key
                let messagesRef = Database.database().reference(withPath: "messages").child(messageId)
                messagesRef.observeSingleEvent(of: .value) { (snapshot) in
                    let message = Message(snapshot: snapshot)
                    let response = ChatsScreen.FetchMessages.Response(messagesDictionary: request.messagesDictionary,
                                                                      message: message, fromUserId: messageFromId)
                    self?.presenter?.presentMessages(response: response)
                }
                
            }
        }
    }
}
