//
//  ChatScreenViewController.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsScreenDisplayLogic: class {
    func displayLoginScreen(viewModel: ChatsScreen.Logout.ViewModel)
    func displayUserName(viewModel: ChatsScreen.FetchUserName.ViewModel)
    func displayMessages(viewModel: ChatsScreen.FetchMessages.ViewModel)
}

class ChatsScreenViewController: UIViewController, ChatsScreenDisplayLogic {
    
    var interactor: ChatsScreenBusinessLogic?
    var router: (NSObjectProtocol & ChatsScreenRoutingLogic & ChatsScreenDataPassing)?
    var messagesTableView: UITableView = {
        let tableView = UITableView()
        tableView.translatesAutoresizingMaskIntoConstraints = false
        return tableView
    }()
    private var messagesDictionarys: [String: ChatsScreen.FetchMessages.ViewModel.MessagesViewModel] = [:]
    private var messagesViewModel: [ChatsScreen.FetchMessages.ViewModel.MessagesViewModel]?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(false, animated: false)
        setup()
        setupNavigationItemLeftButton()
        setupNavigationItemRightButton()
        setupMessagesTableView()
        interactor?.fetchUserName(request: ChatsScreen.FetchUserName.Request())
        interactor?.fetchMessages(request: ChatsScreen.FetchMessages.Request(messagesDictionary: messagesDictionarys))
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    func displayMessages(viewModel: ChatsScreen.FetchMessages.ViewModel) {
        messagesDictionarys = viewModel.messagesDictionary
        messagesViewModel = Array(messagesDictionarys.values)
        messagesTableView.reloadData()
    }
    
    func displayUserName(viewModel: ChatsScreen.FetchUserName.ViewModel) {
        navigationItem.title = viewModel.userName
    }
    
    func displayLoginScreen(viewModel: ChatsScreen.Logout.ViewModel) {
        self.navigationController?.popViewController(animated: true)
    }
    
    private func setupNavigationItemLeftButton() {
        let button = UIBarButtonItem(title: "Logout", style: .plain, target: self, action: #selector(doLogout))
        navigationItem.leftBarButtonItem = button
    }
    
    @objc private func doLogout() {
        interactor?.doLogout(request: ChatsScreen.Logout.Request())
    }
    
    private func setupNavigationItemRightButton() {
        let button = UIBarButtonItem(barButtonSystemItem: .bookmarks, target: self, action: #selector(showAllUsers))
        navigationItem.rightBarButtonItem = button
    }

    @objc private func showAllUsers() {
        let vc = ListOfUsersViewController()
        navigationController?.pushViewController(vc, animated: true)
    }
    
    private func setupMessagesTableView() {
        view.addSubview(messagesTableView)
        messagesTableView.dataSource = self
        messagesTableView.delegate = self
        messagesTableView.register(ListOfUsersTableViewCell.self, forCellReuseIdentifier: "messagesCell")
        
        messagesTableView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        messagesTableView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        messagesTableView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        messagesTableView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
    }
    
    private func setup() {
        let viewController = self
        let interactor = ChatsScreenInteractor()
        let presenter = ChatsScreenPresenter()
        let router = ChatsScreenRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}

extension ChatsScreenViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return messagesViewModel?.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "messagesCell") as! ListOfUsersTableViewCell
        guard let messageViewModel = messagesViewModel?[indexPath.row] else { return UITableViewCell() }
        cell.setupUserMessages(with: messageViewModel)
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
}
