//
//  ChatScreenModels.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChatsScreen {
    // MARK: Use cases
    
    enum FetchUserName {
        struct Request {
        }
        
        struct Response {
            let user: User
        }
        
        struct ViewModel {
            let userName: String
        }
    }
    
    enum Logout {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum FetchMessages {
        struct Request {
            let messagesDictionary: [String: ChatsScreen.FetchMessages.ViewModel.MessagesViewModel]
        }
        
        struct Response {
            let messagesDictionary: [String: ChatsScreen.FetchMessages.ViewModel.MessagesViewModel]
            let message: Message
            let fromUserId: String
        }
        
        struct ViewModel {
            let messagesDictionary: [String: ChatsScreen.FetchMessages.ViewModel.MessagesViewModel]
            
            struct MessagesViewModel {
                let text: String
                let fromUserName: String
                let date: String
            }
        }
    }
}
