//
//  ChatScreenModels.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChatsScreen {
    // MARK: Use cases
    
    enum FetchCurrentUser {
        struct Request {
        }
        
        struct Response {
            let user: User
        }
        
        struct ViewModel {
            let userViewModel: ListOfUsers.FetchUsers.ViewModel.UserViewModel
        }
    }
    
    enum Logout {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum FetchMessages {
        struct Request {
        }
        
        struct Response {
            let message: Message
            let fromUserId: String
            let profileImageURL: String
        }
        
        struct ViewModel {
            let key: String
            let value: ChatsScreen.FetchMessages.ViewModel.MessagesViewModel
            
            struct MessagesViewModel {
                let text: String
                let fromUserName: String
                let profileImageURL: String
                let fromUserId: String
                let date: String
            }
        }
    }
    
    enum FetchUserToStartChating {
        struct Request {
            let userId: String
        }
        
        struct Response {
            let user: User
        }
        
        struct ViewModel {
            let userViewModel: ListOfUsers.FetchUsers.ViewModel.UserViewModel
        }
    }
}
