//
//  SettingsScreenModels.swift
//  LiveChat
//
//  Created by Роман Важник on 29/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SettingsScreen {
    // MARK: Use cases
    
    enum FetchCurrentUserImage {
        struct Request {
        }
        
        struct Response {
            let user: User
        }
        
        struct ViewModel {
            let userURL: String
        }
    }
    
    enum ChangeProfileImage {
        struct Request {
            let image: UIImage
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum ChangeName {
        struct Request {
            let newName: String
        }
        
        struct Response {
            let error: TextError?
        }
        
        struct ViewModel {
            let errorText: String?
        }
    }
}
