//
//  SettingsScreenPresenter.swift
//  LiveChat
//
//  Created by Роман Важник on 29/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsScreenPresentationLogic {
    func presentCurrentUserImage(response: SettingsScreen.FetchCurrentUserImage.Response)
    func presentNewProfileImage(response: SettingsScreen.ChangeProfileImage.Response)
    func presentNewName(response: SettingsScreen.ChangeName.Response)
}

class SettingsScreenPresenter: SettingsScreenPresentationLogic {
    
    weak var viewController: SettingsScreenDisplayLogic?
    
    // MARK: Do something
    
    func presentCurrentUserImage(response: SettingsScreen.FetchCurrentUserImage.Response) {
        let viewModel = SettingsScreen.FetchCurrentUserImage.ViewModel(userURL: response.user.imageURL)
        viewController?.displayCurrentUserImage(viewModel: viewModel)
    }
    
    func presentNewProfileImage(response: SettingsScreen.ChangeProfileImage.Response) {
        viewController?.newImageWasUpload(viewModel: SettingsScreen.ChangeProfileImage.ViewModel())
    }
    
    func presentNewName(response: SettingsScreen.ChangeName.Response) {
        var textError: String?
        if let error = response.error {
            textError = error.description
        }
        viewController?.displayNewUserName(viewModel: SettingsScreen.ChangeName.ViewModel(errorText: textError))
    }
}
