//
//  ChatScreenModels.swift
//  LiveChat
//
//  Created by Роман Важник on 20/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChatScreen {
    // MARK: Use cases
    
    enum SendMessage {
        struct Request {
            let text: String?
            let toId: String
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum FetchMessage {
        struct Request {
            let fromUserId: String
        }
        
        struct Response {
            let fromUserId: String
            let message: Message
        }
        
        struct ViewModel {
            let messageViewModel: MessageViewModel
            
            struct MessageViewModel {
                let textMessage: String?
                let imageURL: String?
                let imageWidth: Double?
                let imageHeight: Double?
                let isMessageFromUser: Bool
                let time: String
                let messageSize: CGRect
            }
        }
    }
    
    enum SendImage {
        struct Request {
            let image: UIImage
            let toId: String
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
