//
//  ChatScreenWorker.swift
//  LiveChat
//
//  Created by Роман Важник on 20/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class ChatScreenWorker {
    func sendMessage(fromUserId: String, toUserId: String, dictionary: [String: Any]) {
        let ref = Database.database().reference(withPath: "messages")
        let messageRef = ref.childByAutoId()
        let currentUserMessageRef = Database.database().reference(withPath: "userMassages").child(fromUserId).child(toUserId)
        let toUserMessageRef = Database.database().reference(withPath: "userMassages").child(toUserId).child(fromUserId)
        messageRef.setValue(dictionary) { (error, ref) in
            let userMassages = [messageRef.key: "1"]
            currentUserMessageRef.updateChildValues(userMassages)
            toUserMessageRef.updateChildValues(userMassages)
        }
    }
}
