//
//  ListOfUsersModels.swift
//  LiveChat
//
//  Created by Роман Важник on 19/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListOfUsers {
    // MARK: Use cases
    
    enum FetchUsers {
        struct Request {
        }
        
        struct Response {
            let users: [User]
        }
        
        struct ViewModel {
            
            let users: [UserViewModel]
            
            struct UserViewModel {
                let userName: String
                let userEmail: String
            }
        }
    }
}
