//
//  ListOfUsersPresenter.swift
//  LiveChat
//
//  Created by Роман Важник on 19/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOfUsersPresentationLogic {
    func presentUsers(response: ListOfUsers.FetchUsers.Response)
}

class ListOfUsersPresenter: ListOfUsersPresentationLogic {
    
    weak var viewController: ListOfUsersDisplayLogic?
    
    // MARK: Do something
    
    func presentUsers(response: ListOfUsers.FetchUsers.Response) {
        var usersViewModel: [ListOfUsers.FetchUsers.ViewModel.UserViewModel] = []
        for item in response.users {
            let userViewModel = ListOfUsers.FetchUsers.ViewModel.UserViewModel(userName: item.name,
                                                                               userEmail: item.email)
            usersViewModel.append(userViewModel)
        }
        let viewModel = ListOfUsers.FetchUsers.ViewModel(users: usersViewModel)
        viewController?.displayUsers(viewModel: viewModel)
    }
}
