//
//  ListOfUsersPresenter.swift
//  LiveChat
//
//  Created by Роман Важник on 19/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol ListOfUsersPresentationLogic {
    func presentUsers(response: ListOfUsers.FetchUsers.Response)
}

class ListOfUsersPresenter: ListOfUsersPresentationLogic {
    
    weak var viewController: ListOfUsersDisplayLogic?
    
    // MARK: Do something
    
    func presentUsers(response: ListOfUsers.FetchUsers.Response) {
        guard let userId = Auth.auth().currentUser?.uid else { return }
        var usersViewModel: [ListOfUsers.FetchUsers.ViewModel.UserViewModel] = []
        for user in response.users {
            if user.id != userId {
                let userViewModel = ListOfUsers.FetchUsers.ViewModel.UserViewModel(userName: user.name,
                                                                                   userEmail: user.email,
                                                                                   userImageURL: user.imageURL,
                                                                                   userId: user.id)
                usersViewModel.append(userViewModel)
            }
        }
        let viewModel = ListOfUsers.FetchUsers.ViewModel(users: usersViewModel)
        viewController?.displayUsers(viewModel: viewModel)
    }
    
}
