//
//  ListOfUsersViewController.swift
//  LiveChat
//
//  Created by Роман Важник on 19/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOfUsersDisplayLogic: class {
    func displayUsers(viewModel: ListOfUsers.FetchUsers.ViewModel)
}

class ListOfUsersViewController: UIViewController, ListOfUsersDisplayLogic {
    
    // MARK: - Properties
    var interactor: ListOfUsersBusinessLogic?
    var router: (NSObjectProtocol & ListOfUsersRoutingLogic & ListOfUsersDataPassing)?
    var configurator: ListOfUsersScreenConfiguratorProtocol = ListOfUsersScreenConfigurator()
    var usersViewModel: [ListOfUsers.FetchUsers.ViewModel.UserViewModel]?
    
    var usersTableView: UITableView = {
        let tableView = UITableView()
        tableView.translatesAutoresizingMaskIntoConstraints = false
        return tableView
    }()
    
    let selectedBackgroundView: UIView = {
        let view = UIView()
        view.backgroundColor = .clear
        return view
    }()
    
    //MARK: - Methods
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Users"
        configurator.configure(viewController: self)
        setupTableView()
        getUsers()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tabBarController?.tabBar.isHidden = false
    }
    
    override func dismiss(animated flag: Bool, completion: (() -> Void)? = nil) {
        super.dismiss(animated: flag, completion: nil)
    }
    
    func getUsers() {
        let request = ListOfUsers.FetchUsers.Request()
        interactor?.fetchUsers(request: request)
    }
    
    func displayUsers(viewModel: ListOfUsers.FetchUsers.ViewModel) {
        usersViewModel = viewModel.users
        usersTableView.reloadData()
    }
    
    private func setupTableView() {
        view.addSubview(usersTableView)
        usersTableView.dataSource = self
        usersTableView.delegate = self
        usersTableView.tableFooterView = UIView()
        usersTableView.backgroundColor = .black
        usersTableView.register(ListOfUsersTableViewCell.self, forCellReuseIdentifier: "usersCell")
        
        usersTableView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        usersTableView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        usersTableView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        usersTableView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
    }
    
}

//MARK: - UITableViewDelegate, UITableViewDataSource
extension ListOfUsersViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return usersViewModel?.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "usersCell", for: indexPath) as! ListOfUsersTableViewCell
        cell.selectedBackgroundView = selectedBackgroundView
        guard let userViewModel = usersViewModel?[indexPath.row] else { return UITableViewCell() }
        cell.setupUserElements(with: userViewModel)
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        guard let user = usersViewModel?[indexPath.row] else { return }
        let vc = ChatScreenViewController()
        vc.user = user
        tableView.deselectRow(at: indexPath, animated: true)
        navigationController?.pushViewController(vc, animated: true)
    }
}
