
//
//  ListOfUsersInteractor.swift
//  LiveChat
//
//  Created by Роман Важник on 19/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol ListOfUsersBusinessLogic {
    func fetchUsers(request: ListOfUsers.FetchUsers.Request)
}

protocol ListOfUsersDataStore {
    //var name: String { get set }
}

class ListOfUsersInteractor: ListOfUsersBusinessLogic, ListOfUsersDataStore {
    
    var presenter: ListOfUsersPresentationLogic?
    var worker: ListOfUsersWorker?
    
    func fetchUsers(request: ListOfUsers.FetchUsers.Request) {
        worker = ListOfUsersWorker()
        worker?.doSomeWork()
        
        let ref = Database.database().reference(withPath: "users")
        ref.observe(.value) { [weak self] (snapshot) in
            var users: [User] = []
            for item in snapshot.children {
                let user = User(snapshot: item as! DataSnapshot)
                users.append(user)
            }
            let response = ListOfUsers.FetchUsers.Response(users: users)
            self?.presenter?.presentUsers(response: response)
        }
    }
}
