//
//  ChatScreenModels.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChatScreen {
    // MARK: Use cases
    
    enum FetchUserName {
        struct Request {
        }
        
        struct Response {
            let user: User
        }
        
        struct ViewModel {
            let userName: String
        }
    }
    
    enum Logout {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
