//
//  ChatScreenInteractor.swift
//  LiveChat
//
//  Created by Роман Важник on 18/02/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol ChatScreenBusinessLogic {
    func doLogout(request: ChatScreen.Logout.Request)
    func fetchUserName(request: ChatScreen.FetchUserName.Request)
}

protocol ChatScreenDataStore {
    //var name: String { get set }
}

class ChatScreenInteractor: ChatScreenBusinessLogic, ChatScreenDataStore {
    
    var presenter: ChatScreenPresentationLogic?
    var worker: ChatScreenWorker?
    
    func doLogout(request: ChatScreen.Logout.Request) {
        do {
            try Auth.auth().signOut()
        } catch {
            print("error")
            return
        }
        let response = ChatScreen.Logout.Response()
        presenter?.userHasLogouted(response: response)
    }
    
    func fetchUserName(request: ChatScreen.FetchUserName.Request) {
        guard let userId = Auth.auth().currentUser?.uid else { return }
        let reference = Database.database().reference(withPath: "users").child(userId)
        reference.observe(.value) { [weak self] (snapshot) in
            let user = User(snapshot: snapshot)
            self?.presenter?.presentUserName(response: ChatScreen.FetchUserName.Response(user: user))
        }
    }
}
